version: '3'
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - 8080:8080
      - 50000:50000
    user: 1000:1001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins_home:/var/jenkins_home
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 443:443
      - 23:22
    volumes:
      -  gitlab_conf:/etc/gitlab
      -  gitlab_logs:/var/log/gitlab
      -  gitlab_data:/var/opt/gitlab
  artifactory:
      image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
      ports: 
        - 8082:8082
        - 8081:8081
      volumes:
      - artifactory:/var/opt/jfrog/artifactory
         

volumes:
  jenkins_home:
  artifactory:
  gitlab_conf:
  gitlab_logs:
  gitlab_data:
